@echo off
echo Installing dependencies...
call npm install

echo Generating Prisma Client...
call npx prisma generate

echo Pushing DB schema...
call npx prisma db push

echo Seeding database...
call npx prisma db seed

echo Starting Next.js app...
call npm run dev
